#last modification: 23.07, Marysia Hayder

def createLetter(fileName, sequence):
    file = open(fileName, "w")
    file.writelines(sequence)
    file.close()


def main():
    fileNamesList = ["n", "i", "c", "e", "f", "g", "h", "j", "l", "s", "t", "u", "y", "polish l", "modificated e"]
    seqsList = ["WSSSSSSSSSSSSSSSSSSSSWWWWWWWWWNNNNNNNNNNNNNNNNNNNNWWWWWWWWWWWSSSSSSSSSSSSSSSSSSSSSENNNNNNNNNNNNNNNNNNNNEEEEEEEEESSSSSSSSSSSSSSSSSSSSEEEEEEEEEEENNNNNNNNNNNNNNNNNNNNN", #n
                "WSSSSSSSSSSSSSSSSSSSSSENNNNNNNNNNNNNNNNNNNNN", #i
                "WWWWWWWWWWWWWWWWWWWWWSSSSSSSSSSSSSSSSSSSSSEEEEEEEEEEEEEEEEEEEEENWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNEEEEEEEEEEEEEEEEEEEEN", #c
                "WWWWWWWWWWWWWWWWWWWWWSSSSSSSSSSSSSSSSSSSSSEEEEEEEEEEEEEEEEEEEEENWWWWWWWWWWWWWWWWWWWWNNNNNNNNNEEEEEEEEEEEEEEEEEEEENWWWWWWWWWWWWWWWWWWWWNNNNNNNNNEEEEEEEEEEEEEEEEEEEEN", #e
                "WWWWWWWWWWWWWWWWWWWWWSSSSSSSSSSSSSSSSSSSSSENNNNNNNNNNNNEEEEEEEEEEEEEEEEEEEENWWWWWWWWWWWWWWWWWWWWNNNEEEEEEEEEEEEEEEEEEEEN", #f
                "WWWWWWWWWWWWWWWWWWWWWSSSSSSSSSSSSSSSSSSSSSEEEEEEEEEEEEEEEEEEEEENNNNNNNNNNNNNWWWWWWWWW WWW WWW S EEE EEE EEE EEE EE SSSSS SSS SSS WWW WWW WWW WWW WWW WWW W NNN NNN NNN NNN NNNNNNN EEE EEE EEE EEE EEE EE EEE N", #g
                "W SSS SSS SSS S WWW WWW WWW WWW WWW WWW W NNN NNN NNN N W SSS SSS SSS SSS SS SSSSSSS E NNN NNN NNN N EEE EEE EEE EEE EEE EEE E SSS SSS SSS S E NNN NNN NNN NNN NNNNNNNNN", #h
                "W SSS SSS SSS SSS SS SSSSSS WWW WWW WWW WWW WWW WWW W NN W SSS EEE EEE EEE EEE EEE EEE EEE NNNNNNNNNN NNN NNN NNN NN", #j
                "W SSS SSS SSS SSS SS SSSSSSS EEE EEE EEE EEE EEE EEE EEE N WWW WWW WWW WWW WWW WWW WW NNN NNN NNN NNN NN NNNNNN", #l
                "WWW WWW WWW WWW WWW WWW WWW SSS SSS SSS SS EEE EEE EEE EEE EEE EE EEE SSS SSS SSS WWW WWW WWW WWW WWW WWW WW S EEE EEE EEE EEE EEE EEE EEE NNN NNN NNN NN WWW WWW WWW WWW WWW WWW WW NNN NNN NNN EEE EEE EEE EEE EEE EE EEEN", #s
                "WWW WWW WWW WWW WWW WWW WWW S EEE EEE EEE E SSSSSS SSS SSS SSS SSS SS E NNNNNNNNN NNN NNN NNN NN EEE EEE EEE E N", #t
                "W SSS SSS SSS SSS SS SSSSSS WWW WWW WWW WWW WWW WWW W NNNNNNNNN NNN NNN NNN NN W SSSSSSS SSS SSS SSS SSS SS EEE EEE EEE EEE EEE EEE EEE NNN NNN NNN NNN NNNNNNNNN", #u
                " W SSS SSS SS WWW WWW WWW WWW WWW WWW W NN NNN NNN W SSS SSS SSS EEE EEE EEE E SSSS SSS SSS SS E NNN NNN NNN NNN EEE EEE EEE  E NNN NNN NNN", #y
                "WWW WWW WWW W NN NNN NNN W SS SSS SSS SS WWW WWW WWW W S EEE EEE EEE E SSSS SSS SSS SS EEE EEE EEE EE N WWW WWW WWW W NNN NNN NNNN NN EEE EEE EEE E N",  #polish l
                "WWW WWW WWW WWW WWW WWW WWW SSS SSS SSS SSS SS SSSSSSS EEE EEE EEE EEE EEE EEE EEE  N WWW WWW WWW WWW WWW WWW WW NNN NNN NNN NNN NNN EEE EEE EEE EEE EEE EEE EE N WWW WWW WWW WWW WWW WWW WW NNN EEE EEE EEE EEE EEE EEE EE N"] #mod e


    i = 0
    while i < len(fileNamesList):
        createLetter(fileNamesList[i], seqsList[i])
        i = i + 1

    return 0


if __name__ == '__main__':
    import sys

    sys.exit(main())


